In [589]:
import os
import rasterio
import numpy as np
from datetime import datetime, timedelta

# # Folder path containing .tif files
# folder_path = "/mnt/data1tb/BRIOS/data2/ndvi_8days"

# # Dates with no data
# missing_dates = ['2023-01-05', '2023-02-06', '2023-02-14', '2023-03-26',
#                  '2023-04-03', '2023-04-11', '2023-04-19', '2023-04-27']
# missing_dates = set(missing_dates)  # Convert to set for quick lookups

# # List of all available dates
# available_files = [f for f in os.listdir(folder_path) if f.endswith('.tif')]
# available_dates = sorted(
#     datetime.strptime(f.split('_')[1].split('.')[0], "%Y-%m-%d") for f in available_files
# )

# # Check raster dimensions from a sample file
# with rasterio.open(os.path.join(folder_path, available_files[0])) as src:
#     height, width = src.shape

# # Initialize list to hold time series data
# time_series = []

# # Generate the complete list of dates, assuming an 8-day interval
# start_date = available_dates[0]
# end_date = available_dates[-1]
# current_date = start_date

# while current_date <= end_date:
#     date_str = current_date.strftime("%Y-%m-%d")
#     file_path = os.path.join(folder_path, f"ndvi8days_{date_str}.tif")
    
#     if date_str in missing_dates or not os.path.exists(file_path):
#         # Append a null array for missing dates
#         null_array = np.full((height, width), np.nan)
#         time_series.append(null_array)
#     else:
#         # Read and store data for available dates
#         with rasterio.open(file_path) as src:
#             time_series.append(src.read(1))  # Reads the first band

#     # Increment by 8 days
#     current_date += timedelta(days=8)

# # Stack along the time dimension, then transpose to (x, y, time)
# ndvi_data = np.stack(time_series, axis=0).transpose(1, 2, 0)

# # Save as .npy file
output_path = "/mnt/data1tb/BRIOS/data2/ndvi_timeseries.npy"
# np.save(output_path, ndvi_data)

# print(f"Data saved to {output_path}")


In [590]:
ndvi = np.load(output_path)

ndvi.shape

(342, 470, 46)

In [591]:
# # Folder path containing RVI .tif files
# folder_path = "/mnt/data1tb/BRIOS/hiephoa_kinhmon/rvi_8days_test"

# # List all available .tif files in the folder
# available_files = sorted([f for f in os.listdir(folder_path) if f.endswith('.tif')])

# # Check raster dimensions from a sample file
# with rasterio.open(os.path.join(folder_path, available_files[0])) as src:
#     height, width = src.shape

# # Initialize lists to hold RVI and VH time series data
# rvi_time_series = []
# vh_time_series = []

# # Read and store RVI and VH data from each file
# for file_name in available_files:
#     file_path = os.path.join(folder_path, file_name)
#     with rasterio.open(file_path) as src:
#         # Append the first band for RVI data
#         rvi_time_series.append(src.read(1))  # RVI is in band 1
#         # Append the second band for VH data
#         vh_time_series.append(src.read(2))  # VH is in band 2

# # Stack along the time dimension and transpose to (x, y, time)
# rvi_data = np.stack(rvi_time_series, axis=0).transpose(1, 2, 0)
# vh_data = np.stack(vh_time_series, axis=0).transpose(1, 2, 0)

# print(f"rvi: {rvi_data.shape}")
# print(f"vh: {vh_data.shape}")

# # Save each time series as .npy file
# output_rvi_path = "/mnt/data1tb/BRIOS/hiephoa_kinhmon/rvi_timeseries.npy"
# output_vh_path = "/mnt/data1tb/BRIOS/hiephoa_kinhmon/vh_timeseries.npy"
# np.save(output_rvi_path, rvi_data)
# np.save(output_vh_path, vh_data)

# print(f"RVI data saved to {output_rvi_path}")
# print(f"VH data saved to {output_vh_path}")


In [592]:
rvi_data = np.load('/mnt/data1tb/BRIOS/dataTrain/rvi_full.npy')
vh_data = np.load('/mnt/data1tb/BRIOS/dataTrain/vh_full.npy')

luu x y

In [593]:
ndvi_data = ndvi
ndvi_data.shape

(342, 470, 46)

In [594]:
x, y, t = ndvi_data.shape

In [595]:
# coordinates_first = np.array([(i, j) for i in range(x) for j in range(y)])

In [596]:
# coordinates_first[1]

In [597]:
ndvi_data = ndvi_data.reshape((ndvi_data.shape[0] * ndvi_data.shape[1], ndvi_data.shape[2]))
rvi_data = rvi_data.reshape((rvi_data.shape[0] * rvi_data.shape[1], rvi_data.shape[2]))
vh_data = vh_data.reshape((vh_data.shape[0] * vh_data.shape[1], vh_data.shape[2]))

In [598]:
time_series_less_null = np.load('/mnt/data1tb/BRIOS/data2/anphu_less_null.npy')
ndvi_data = ndvi_data[time_series_less_null]
rvi_data = rvi_data[time_series_less_null]
vh_data = vh_data[time_series_less_null]

In [599]:
ndvi_data.shape

(1384, 46)

In [600]:
ndvi_data

array([[       nan,        nan, 0.4392558 , ..., 0.42815393, 0.27344027,
        0.27344027],
       [       nan,        nan, 0.53755772, ..., 0.62836951, 0.59185058,
        0.59185058],
       [       nan,        nan, 0.54158568, ..., 0.71329784, 0.71155685,
        0.71155685],
       ...,
       [0.69387758, 0.69387758, 0.71141648, ..., 0.79825151, 0.66508889,
        0.62909091],
       [0.68592262, 0.68592262, 0.70181435, ..., 0.78972769, 0.65482491,
        0.65482491],
       [0.67317343, 0.67317343, 0.70294964, ..., 0.79163814, 0.64478475,
        0.64478475]])

In [601]:
rvi_data.shape

(1384, 46)

In [602]:
vh_data.shape

(1384, 46)

# Make cloudMask
- `ndvi_data[i]` == `np.nan` => have cloud
- `cloudMask[i] = 0`: no cloud 
- `cloudMask[i]` = 1: cloud

In [603]:
cloudMask = np.zeros(ndvi_data.shape)

In [604]:
cloudMask.shape

(1384, 46)

In [605]:
for series_index in range(ndvi_data.shape[0]):
    for time_step in range(ndvi_data.shape[1]):
        if np.isnan(ndvi_data[series_index, time_step]):
            cloudMask[series_index, time_step] = 1

In [606]:
print(f'so gia tri = 1 trong cloudmask = {np.sum(cloudMask==1)}')
print(f'so gia tri = 0 trong cloudmask = {np.sum(cloudMask==0)}')

so gia tri = 1 trong cloudmask = 18705
so gia tri = 0 trong cloudmask = 44959


random 25, 50, 75% fake cloud

In [607]:
def fake_cloud_ratio(cloud_mask, ratio):
    # Tạo một mảng boolean cùng kích thước với cloud_mask để lưu vị trí thay đổi
    changed_positions = np.zeros_like(cloud_mask, dtype=bool)
    
    # Lặp qua từng mẫu (theo hàng i)
    for i in range(cloud_mask.shape[0]):
        # Lấy các chỉ số của các vị trí có giá trị 0 tại hàng i
        zero_indices = np.where(cloud_mask[i, :] == 0)[0]
        
        # Tính số lượng phần tử cần chuyển từ 0 thành 1 theo tỷ lệ ratio
        num_to_flip = int(len(zero_indices) * ratio)
        print(num_to_flip)
        
        # Chọn ngẫu nhiên các chỉ số trong số các chỉ số có giá trị 0
        if num_to_flip > 0:
            flip_indices = np.random.choice(zero_indices, size=num_to_flip, replace=False)
            
            # Đổi các giá trị tại các vị trí được chọn thành 1 trong cloud_mask
            cloud_mask[i, flip_indices] = 1
            
            # Đánh dấu các vị trí đã thay đổi trong mảng changed_positions
            changed_positions[i, flip_indices] = True

    return cloud_mask, changed_positions


In [608]:
cloudMask, changed_positions = fake_cloud_ratio(cloud_mask=cloudMask, ratio=0.75)

np.save('/mnt/data1tb/BRIOS/data2/changed_positions_75.npy', changed_positions)

24
24
24
24
24
24
24
24
25
25
25
25
25
24
24
24
24
24
24
24
24
25
25
25
25
24
24
24
24
24
24
25
25
25
25
25
25
24
24
24
24
24
24
24
25
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
2

In [609]:
print(f'so gia tri = 1 trong cloudmask = {np.sum(cloudMask==1)}')
print(f'so gia tri = 0 trong cloudmask = {np.sum(cloudMask==0)}')

so gia tri = 1 trong cloudmask = 52053
so gia tri = 0 trong cloudmask = 11611


# Make mask valid data (data can be used for training)
- data_num: count the number of observations without cloud in each series

In [610]:
data_num = np.full(ndvi_data.shape[0], ndvi_data.shape[1])

In [611]:
data_num.shape

(1384,)

In [612]:
for series_index in range(cloudMask.shape[0]):
    num_ones = len(np.argwhere(cloudMask[series_index] == 1))
    data_num[series_index] -= num_ones

In [613]:
data_num

array([8, 8, 8, ..., 8, 8, 8])

In [614]:
valid_with_data_num = np.argwhere(data_num >= 1)

In [615]:
len(valid_with_data_num)

1384

In [616]:
rvi_data.shape

(1384, 46)

mask sar
- 1: unvalid (sar get nan) 
- 0: valid (fully data)

In [617]:
unvalid_rvi = np.where(np.isnan(rvi_data).any(axis=1), 1, 0)

In [618]:
print(unvalid_rvi)

[0 0 0 ... 0 0 0]


In [619]:
unvalid_vh = np.where(np.isnan(vh_data).any(axis=1), 1, 0)

In [620]:
print(unvalid_vh)

[0 0 0 ... 0 0 0]


In [621]:

combined_mask = np.where(np.logical_or(unvalid_rvi == 1, unvalid_vh == 1), 1, 0)

make mask Train

In [622]:
index_for_train = np.where((data_num >= 1) & (combined_mask == 0))[0]

In [623]:
def choose_data_validate(arr_index, valid_ratio = 0.0):
    num_valid = max(1, int(valid_ratio * len(arr_index)))
    index_for_valid = np.random.choice(arr_index, num_valid, replace=False)
    return index_for_valid

In [624]:
len(index_for_train)

1384

luu x y sau khi chon index

In [625]:
# coordinates_second = coordinates_second = coordinates_first[index_for_train]

In [626]:
# coordinates_second[0]

In [627]:
# np.save('/mnt/data1tb/BRIOS/dataTrain/coordinates.npy', coordinates_second)

In [628]:
cloudMask0 = cloudMask

In [629]:
np.where(cloudMask[942] == 0)[0]

array([ 0,  3, 27, 28, 29, 34, 35, 41, 43])

In [630]:
# for series_index in index_for_train:
#     uncloud_index = np.where(cloudMask0[series_index] == 0)[0]
#     fakecloud_index = choose_data_validate(uncloud_index)
#     cloudMask0[series_index, fakecloud_index] = 2

In [631]:
ndvi_input = ndvi_data[index_for_train]
rvi_input = rvi_data[index_for_train]
vh_input = vh_data[index_for_train]

In [632]:
cloudmask_input = cloudMask0[index_for_train]

In [633]:
cloudmask_input[0]

array([1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.])

In [634]:
ndvi_input[0]

array([       nan,        nan, 0.4392558 , 0.43852931, 0.4696635 ,
       0.42532909, 0.44989339, 0.3755179 ,        nan, 0.55950755,
       0.43296704, 0.36270413,        nan, 0.34070158, 0.34070158,
              nan,        nan,        nan, 0.19552609, 0.19183846,
       0.20591967, 0.22343096,        nan,        nan,        nan,
              nan,        nan,        nan, 0.19717787, 0.19717787,
       0.20403515, 0.24450952, 0.29652864,        nan, 0.35159817,
       0.392658  , 0.45704058, 0.27272728, 0.27272728, 0.36832413,
       0.36832413, 0.52253461, 0.50308371, 0.42815393, 0.27344027,
       0.27344027])

In [635]:
mask_train = np.where(cloudmask_input == 0, 1, 0)
mask_eval = np.where(cloudmask_input == 2, 1, 0)

In [636]:
# mask_train[:] = 1


In [637]:
mask_train[0]

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1])

In [638]:
mask_eval[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [639]:
input_data = np.stack([rvi_input, vh_input, ndvi_input], axis=1)

In [640]:
input_data.shape

(1384, 3, 46)

In [641]:
input_data[0,2,:]

array([       nan,        nan, 0.4392558 , 0.43852931, 0.4696635 ,
       0.42532909, 0.44989339, 0.3755179 ,        nan, 0.55950755,
       0.43296704, 0.36270413,        nan, 0.34070158, 0.34070158,
              nan,        nan,        nan, 0.19552609, 0.19183846,
       0.20591967, 0.22343096,        nan,        nan,        nan,
              nan,        nan,        nan, 0.19717787, 0.19717787,
       0.20403515, 0.24450952, 0.29652864,        nan, 0.35159817,
       0.392658  , 0.45704058, 0.27272728, 0.27272728, 0.36832413,
       0.36832413, 0.52253461, 0.50308371, 0.42815393, 0.27344027,
       0.27344027])

have dataset contains: 
- input data: [rvi, vh, ndvi] (n_series, n_features, n_timesteps)
- mask_train: 1 => training, 0 => no
- mask_eval: 1 => validating, 0 => no

Create delta

In [642]:
def cal_timestep(time, mask):
    """calculate timestep (between step t to step t-i nearest without cloud)

    Args:
        time (_type_): _description_
        mask (_type_): _description_

    Returns:
        deltaT: timestep
    """
    deltaT = time.copy()
    for i in range(len(time)):
        T_time0 = time[i]
        if i != 0:
            for k in range(i - 1, -1, -1):
                T_time1 = time[k]
                if mask[k] == 1:
                    T_time1 = time[k]
                    break

            T = T_time0-T_time1
        else:
            T = 0

        deltaT[i] = T

    return deltaT

In [643]:
feature_num = 3
time = np.arange(1,369,8)
deltaT_forward = np.zeros((len(index_for_train), 46))
for i in range(len(index_for_train)):
    maskone = mask_train[i, :]
    done = cal_timestep(time, maskone)
    deltaT_forward[i, :] = done

In [644]:
deltaT_backward = np.zeros((len(index_for_train), 46))
for i in range(len(index_for_train)):
    maskone = mask_train[i, :]
    maskone = maskone[::-1]
    done = cal_timestep(time, maskone)
    deltaT_backward[i, :] = done

In [645]:
deltaT_backward[0]

array([  0.,   8.,  16.,  24.,  32.,  40.,   8.,  16.,  24.,  32.,  40.,
        48.,  56.,  64.,   8.,  16.,   8.,  16.,  24.,  32.,  40.,  48.,
        56.,  64.,  72.,  80.,  88.,   8.,  16.,  24.,  32.,  40.,  48.,
        56.,  64.,  72.,  80.,  88.,  96., 104.,   8.,   8.,  16.,  24.,
         8.,  16.])

In [646]:
deltaT_forward[0]

array([  0.,   8.,  16.,   8.,  16.,  24.,   8.,   8.,  16.,  24.,  32.,
        40.,  48.,  56.,  64.,  72.,  80.,  88.,  96., 104.,   8.,  16.,
        24.,  32.,  40.,  48.,  56.,  64.,  72.,  80.,  88.,   8.,  16.,
         8.,  16.,  24.,  32.,  40.,  48.,  56.,  64.,   8.,  16.,  24.,
        32.,  40.])

In [647]:
mask_train[0]

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1])

In [648]:
print('Generate time interval for SAR data: ')
deltaTt = np.zeros((len(index_for_train), 46))
for i in range(len(index_for_train)):
    maskone = np.ones(46)
    maskone = np.int_(maskone)
    done = cal_timestep(time, maskone)
    deltaTt[i, :] = done


Generate time interval for SAR data: 


In [649]:
deltaTt[0]

array([0., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

make backward input value 

In [650]:
ndvi_input_backward = ndvi_input[:, ::-1]
rvi_input_backward = rvi_input[:, ::-1]
vh_input_backward = vh_input[:, ::-1]

In [651]:
input_data_backward = np.stack([rvi_input_backward, vh_input_backward, ndvi_input_backward], axis=1)

In [652]:
input_data_backward.shape

(1384, 3, 46)

# Final create dataset

In [653]:
n_timesteps = 46

In [654]:
traindatasets_valuesF = np.empty((n_timesteps, 3, 0),dtype=np.float16)
traindatasets_evalmaskF = np.empty((n_timesteps, 0),dtype=np.int8)
traindatasets_maskF = np.empty((n_timesteps, 0),dtype=np.int8)
traindatasets_deltaF = np.empty((n_timesteps, 3, 0),dtype=np.float16)
traindatasets_deltaBF = np.empty((n_timesteps, 3, 0),dtype=np.float16)

In [655]:
print('Generate training datasets: ')
trainingdatasets_values = np.zeros((46,3, len(index_for_train)))
for step in range(46):
    for series_index in range(len(index_for_train)):
        trainingdatasets_values[step, 0, series_index] = vh_input[series_index, step]
        trainingdatasets_values[step, 1, series_index] = rvi_input[series_index, step]
        if np.isnan(ndvi_input[series_index, step]):
            trainingdatasets_values[step, 2, series_index] = -100
        else:
            trainingdatasets_values[step, 2, series_index] = ndvi_input[series_index, step]
traindatasets_valuesF = np.concatenate((traindatasets_valuesF, trainingdatasets_values), axis=2)

Generate training datasets: 


In [656]:
print('Generate evalmask: ')
traindatasets_evalmask = np.zeros((46,len(index_for_train)), dtype=np.int8)
for step in range(46):
    for series_index in range(len(index_for_train)):
        traindatasets_evalmask[step, series_index] = mask_eval[series_index, step]
traindatasets_evalmaskF = np.concatenate((traindatasets_evalmaskF, traindatasets_evalmask), axis=1)

Generate evalmask: 


In [657]:
print('Generate mask tran: ')
traindatasets_mask = np.zeros((46, len(index_for_train)), dtype=np.int8)
for step in range(46):
    for series_index in range(len(index_for_train)):
        traindatasets_mask[step, series_index] = mask_train[series_index, step]
traindatasets_maskF = np.concatenate((traindatasets_maskF, traindatasets_mask), axis=1)
        

Generate mask tran: 


In [658]:
print('Generate training delta datasets: ')
traindatasets_delta = np.zeros((46, 3, len(index_for_train)), dtype=np.float16)
for step in range(46):
    for series_index in range(len(index_for_train)):
        traindatasets_delta[step, 0, series_index] = deltaTt[series_index, step]
        traindatasets_delta[step, 1, series_index] = deltaTt[series_index, step]
        traindatasets_delta[step, 2, series_index] = deltaT_forward[series_index, step]
traindatasets_deltaF = np.concatenate((traindatasets_deltaF, traindatasets_delta), axis=2)

Generate training delta datasets: 


In [659]:
print('Generate training delta dataset backward: ')
traindatasets_delta_backward = np.zeros((46, 3, len(index_for_train)), dtype=np.float16)
for step in range(46):
    for series_index in range(len(index_for_train)):
        traindatasets_delta_backward[step, 0, series_index] = deltaTt[series_index, step]
        traindatasets_delta_backward[step, 1, series_index] = deltaTt[series_index, step]
        traindatasets_delta_backward[step, 2, series_index] = deltaT_backward[series_index, step]
traindatasets_deltaBF = np.concatenate((traindatasets_deltaBF, traindatasets_delta_backward), axis=2)

Generate training delta dataset backward: 


In [660]:
traindatasets_valuesF.shape

(46, 3, 1384)

In [661]:
traindatasets_maskF

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 1],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int8)

In [662]:
cloudMask0.shape

(1384, 46)

# Save dataset to json

In [663]:
import numpy as np
import json
from tqdm import tqdm

In [664]:
def parse_rec(values, masks, eval_masks, deltas):
    rec = []
    for i in range(values.shape[0]):
        recone = {}
        recone['deltas'] = deltas[i, :].tolist()
        recone['masks'] = masks[i].astype('int8').tolist()
        recone['values'] = values[i, :].astype('float32').tolist()
        recone['eval_masks'] = eval_masks[i].astype('int8').tolist()
        rec.append(recone)
    return rec

In [665]:
def parse_idTrain(id_):
    values = traindatasets_valuesF[:, :, id_]
    masks = traindatasets_maskF[:, id_]
    eval_masks = traindatasets_evalmaskF[:, id_]
    deltas = traindatasets_deltaF[:, :, id_]
    deltasB = traindatasets_deltaBF[:, :, id_]

    rec = {}

    rec['forward'] = parse_rec(values, masks, eval_masks, deltas)
    rec['backward'] = parse_rec(values[::-1], masks[::-1], eval_masks[::-1], deltasB)

    rec = json.dumps(rec)
    fs.write(rec + '\n')

In [666]:
dir = '/mnt/data1tb/BRIOS/dataTrain/'
fs = open(dir + 'anphu_kinhmon_75.json', 'w')
all_len = traindatasets_valuesF.shape[2]
print('Save training dataset as JSON: ')
for id_ in tqdm(range(all_len)):
    parse_idTrain(id_)
fs.close()

Save training dataset as JSON: 


100%|██████████| 1384/1384 [00:01<00:00, 1338.59it/s]


In [667]:
# test = np.load('/mnt/storage/huyekgis/brios/BRIOS/models/res.npy')

In [668]:
# test.shape