In [1]:
import numpy as np

In [6]:
M = np.array([
    [1, 1, 1, 1, 1, 1, 0],
    [0, 1, 1, 1, 0, 0, 1],
    [1, 1, 1, 1, 0, 1, 0],
    [0, 1, 1, 1, 1, 0, 1],
    [1, 1, 1, 1, 1, 1, 1]
])

In [7]:
M.shape

(5, 7)

In [18]:
def solve(arr, n):
    rows, cols = arr.shape
    res = []
    for i in range(rows - n + 1):
        for j in range(cols - n + 1):
            subarr = arr[i:i+n, j:j+n]
            if np.all(subarr==1):
                res.append((i,j))
                print(subarr)
    return res
final_res = []
for i in range(1, min(M.shape[0], M.shape[1])):
    list_sub_arr = solve(M,i)
    final_res.append(list_sub_arr)

1
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
[[1]]
2
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
[[1 1]
 [1 1]]
3
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
4


In [17]:
for arr in final_res:
    print(arr)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7)]
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 1), (1, 2), (1, 3), (1, 6), (2, 0), (2, 1), (2, 2), (2, 3), (2, 5), (3, 1), (3, 2), (3, 3), (3, 4), (3, 6), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6)]
[(0, 1), (0, 2), (1, 1), (1, 2), (2, 1), (2, 2), (3, 1), (3, 2), (3, 3)]
[(0, 1), (1, 1), (2, 1)]
[]


In [25]:
import numpy as np

def find_nxn_subarrays_with_ones(matrix, n):
    rows, cols = matrix.shape
    dp = np.zeros((rows, cols), dtype=int)
    results = []

    for i in range(rows):
        for j in range(cols):
            if matrix[i][j] == 1:
                if i == 0 or j == 0:
                    dp[i][j] = 1
                else:
                    dp[i][j] = min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) + 1
                
                # Kiểm tra nếu tồn tại mảng con n x n
                if dp[i][j] >= n:
                    results.append((i - n + 1, j - n + 1))  # Góc trên bên trái của mảng con

    return results

# Ma trận đầu vào
M = np.array([
    [1, 1, 1, 1, 1, 1, 0],
    [0, 1, 1, 1, 0, 0, 1],
    [1, 1, 1, 1, 0, 1, 0],
    [0, 1, 1, 1, 1, 0, 1],
    [1, 1, 1, 1, 1, 1, 1]
])

# Tìm các mảng con 3x3 toàn số 1
n = 5
res = []
for i in range(1, n):
    subarrays = find_nxn_subarrays_with_ones(M, n)
    res.append(subarrays)

print(res)




[[], [], [], []]
